[server]
enableStaticServing = true

[theme]
base = 'dark'
font = "Alexandria:https://fonts.googleapis.com/css2?family=Alexandria:ital,wght@0,400..700;1,400..700&display=swap"
backgroundColor = "#292C42"
dataframeBorderColor = "#32344a"
dataframeHeaderBackgroundColor = "#32344A"
textColor = '#ffffff'

[theme.sidebar]
primaryColor = "#0076B8"
backgroundColor = "#32344A"
secondaryBackgroundColor = "292C42"

