[server]
enableStaticServing = true

[theme]
base = 'dark'
font = "Alexandria:https://fonts.googleapis.com/css2?family=Alexandria:ital,wght@0,400..700;1,400..700&display=swap"
backgroundColor = "#292C42"
dataframeBorderColor = "#32344a"
dataframeHeaderBackgroundColor = "#292C42"
textColor = '#ffffff'

[theme.sidebar]
primaryColor = "#F1C647"
backgroundColor = "#101222"
